# Generated by Django 6.0.4 on 2026-04-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePsyCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hope', models.FloatField(default=0.0)),
                ('efficacy', models.FloatField(default=0.0)),
                ('resilience', models.FloatField(default=0.0)),
                ('optimism', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
